command_categories:
  - autogpt.app
  - autogpt.commands.analyze_code
  - autogpt.commands.audio_text
  - autogpt.commands.execute_code
  - autogpt.commands.file_operations
  - autogpt.commands.git_operations
  - autogpt.commands.google_search
  - autogpt.commands.image_gen
  - autogpt.commands.improve_code 
  - autogpt.commands.twitter
  - autogpt.commands.web_selenium
  - autogpt.commands.write_tests

disabled_command_categories:  [] 
