site_name: Auto-GPT
site_url: https://docs.agpt.co/
repo_url: https://github.com/Significant-Gravitas/Auto-GPT
nav:
  - Home: index.md
  - Setup: setup.md
  - Usage: usage.md
  - Plugins: plugins.md
  - Configuration:
    - Search: configuration/search.md
    - Memory: configuration/memory.md
    - Voice: configuration/voice.md
    - Image Generation: configuration/imagegen.md

  - Contributing:
    - Contribution guide: contributing.md
    - Running tests: testing.md
    - Code of Conduct: code-of-conduct.md

  - Challenges:
    - Introduction: challenges/introduction.md
    - List of Challenges:
      - General:
        - Looping: challenges/looping.md
      - Tasks:
        - Tasking: challenges/tasking/tasks.md
      - Compliance:
        - Constraints: challenges/compliance/compliance-with-constraints.md
        - Performance: challenges/compliance/compliance-with-performance.md  
      - Planning:
        - Coordination: challenges/planning/coordination.md
        - Plans: challenges/planning/planning.md 
        - Tool use: challenges/tool-use/using-tools.md
        - Evaluating Options: challenges/options/explorations.md
        - Strategy: challenges/strategize/strategies.md
      - Learning:
        - Trial and Error: challenges/experiential/trial_and_error.md
        - Educated Guessing: challenges/experiential/educated_guess.md
        - Experience: challenges/experiential/experience.md
        - Reward via CPU/RAM tracking: challenges/fitness_function/reward_system.md
        - Reward via feedback tracking: challenges/fitness_function/feedback_tracking.md
      - Memory:
        - Introduction: challenges/memory/introduction.md
        - Memory Challenge A: challenges/memory/challenge_a.md
        - Memory Challenge B: challenges/memory/challenge_b.md
        - Memory Challenge C: challenges/memory/challenge_c.md
      - Information retrieval:
        - Introduction: challenges/information_retrieval/introduction.md
        - Information Retrieval Challenge A: challenges/information_retrieval/challenge_a.md
        - Read The Fine Manual: challenges/information_retrieval/rtfm.md
  - Submit a Challenge: challenges/submit.md
  - Beat a Challenge: challenges/beat.md

  - License: https://github.com/Significant-Gravitas/Auto-GPT/blob/master/LICENSE

theme: readthedocs

markdown_extensions:
  admonition:
  codehilite:
  pymdownx.keys:
