[build-system]
requires = ["hatchling", "hatch-requirements-txt"]
build-backend = "hatchling.build"

[project]
name = "agpt"
version = "0.4.3"
authors = [
  { name="Torantulino", email="support@agpt.co" },
]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
description = "An open-source attempt to make GPT-4 autonomous"
dynamic = ["dependencies"]

[project.urls]
"Homepage" = "https://github.com/Significant-Gravitas/Auto-GPT"
"Bug Tracker" = "https://github.com/Significant-Gravitas/Auto-GPT"

[tool.hatch.metadata]
allow-direct-references = true

[project.scripts]
autogpt = "agpt.autogpt.cli:main"

[tool.hatch.build.targets.wheel.force-include]
"autogpt" = "agpt/autogpt"
"autogpt.*" = "agpt/autogpt/*"
"scripts" = "agpt/scripts"
"scripts.*" = "agpt/scripts/*"
"benchmarks.py" = "agpt/benchmarks.py"
"bootstrap" = "agpt/bootstrap"
"bootstrap.*" = "agpt/bootstrap/*"
"data_ingestion.py" = "agpt/data_ingestion.py"
"main.py" = "agpt/main.py"

[tool.hatch.metadata.hooks.requirements_txt]
files = ["requirements_pypi.txt"]

[tool.black]
line-length = 88
target-version = ['py310']
include = '\.pyi?$'
packages = ["autogpt"]
extend-exclude = '.+/(dist|.venv|venv|build)/.+'


[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "FIRSTPARTY",
    "LOCALFOLDER"
]
skip = '''
    .tox
    __pycache__
    *.pyc
    .env
    venv*/*
    .venv/*
    reports/*
    dist/*

'''

[tool.pytest.ini_options]
markers = [
    "requires_openai_api_key",
    "requires_huggingface_api_key"
]
